"""add_indexes_party_name_riding_name

Revision ID: 6f626f339675
Revises: c952b21da691
Create Date: 2026-01-22 23:32:57.767937

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f626f339675'
down_revision: Union[str, None] = 'c952b21da691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_parties_name', 'parties', ['name'], unique=False)
    op.create_index('ix_ridings_name', 'ridings', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ridings_name', table_name='ridings')
    op.drop_index('ix_parties_name', table_name='parties')
    # ### end Alembic commands ###
