"""initial schema

Revision ID: c952b21da691
Revises: 
Create Date: 2026-01-22 22:42:12.632078

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c952b21da691'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ridings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=False),
    sa.Column('fed_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ridings_fed_number', 'ridings', ['fed_number'], unique=False)
    op.create_index('ix_ridings_province', 'ridings', ['province'], unique=False)
    op.create_table('representatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoc_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('honorific', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('riding_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['riding_id'], ['ridings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hoc_id')
    )
    op.create_index('ix_representatives_hoc_id', 'representatives', ['hoc_id'], unique=False)
    op.create_index('ix_representatives_is_active', 'representatives', ['is_active'], unique=False)
    op.create_index('ix_representatives_name', 'representatives', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_representatives_name', table_name='representatives')
    op.drop_index('ix_representatives_is_active', table_name='representatives')
    op.drop_index('ix_representatives_hoc_id', table_name='representatives')
    op.drop_table('representatives')
    op.drop_index('ix_ridings_province', table_name='ridings')
    op.drop_index('ix_ridings_fed_number', table_name='ridings')
    op.drop_table('ridings')
    op.drop_table('parties')
    # ### end Alembic commands ###
